name = "abogadosecuador"
# Worker ultra optimizado - soluciona error 1042 y favicon.ico
main = "cloudflare-worker-clean.js"
compatibility_date = "2025-04-23"
# Usar variable de entorno para account_id en tiempo de despliegue
account_id = "06ea65e2b51d0f23f0c44f92962ac95d" # Se recomienda configurar esto mediante --env durante el despliegue
workers_dev = true

# Configurar el worker como un módulo ES para soportar bindings D1
[build]
command = "npm run build"

# Configuración simplificada para máxima compatibilidad
[site]
bucket = "./dist"

# Configuración de entorno (production)
[env.production]
name = "abogadosecuador"
routes = [
  "abogadosecuador.workers.dev/*"
]

# Variables de entorno - NOTA: Las claves sensibles deben configurarse mediante la UI de Cloudflare o CLI
[env.production.vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
API_ENABLED = "true"
SUPABASE_URL = "https://kbybhgxqdefuquybstqk.supabase.co"
# SUPABASE_KEY debe configurarse a través de variables secretas
CLIENT_VERSION = "3.0.0"
DISABLE_MULTIPLE_CLIENTS = "true"
N8N_WEBHOOK_URL = "https://n8nom.onrender.com/webhook/1cfd2baa-f5ec-4bc4-a99d-dfb36793eabd"
WHATSAPP_NUMBER = "+59398835269"
CONTACT_EMAIL = "Wifirmalegal@gmail.com"

# KV Namespaces (production)
[[env.production.kv_namespaces]]
binding = "ABOGADO_WILSON_KV"
id = "d977cf29acc749ba8aeabbcb2d395cb3"

# D1 Databases (production)
[[env.production.d1_databases]]
binding = "ABOGADO_WILSON_DB"
database_name = "abogado-wilson-db"
database_id = "f00d15a2-6069-4f19-a8eb-6f2217af2176"

# Secretos (para configurar mediante wrangler secret o la UI de Cloudflare)
# wrangler secret put SUPABASE_KEY --env production --name abogadosecuador
# wrangler secret put TURSO_AUTH_TOKEN --env production --name abogadosecuador
# wrangler secret put JWT_SECRET --env production --name abogadosecuador
# wrangler secret put CLOUDFLARE_API_TOKEN --env production --name abogadosecuador
# wrangler secret put N8N_API_KEY --env production --name abogadosecuador
# wrangler secret put TURNSTILE_SECRET_KEY --env production --name abogadosecuador
