name = "abogado-wilson-local"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[dev]
port = 8787
local = true
upstream_protocol = "http"

[env.local]
name = "abogado-wilson-local"
vars = { ENVIRONMENT = "local" }

[[env.local.kv_namespaces]]
binding = "CACHE"
id = "d977cf29acc749ba8aeabbcb2d395cb3"
preview_id = "d977cf29acc749ba8aeabbcb2d395cb3"

[[env.local.d1_databases]]
binding = "DB"
database_name = "abogado-wilson-db"
database_id = "f00d15a2-6069-4f19-a8eb-6f2217af2176"

[env.local.vars]
ENVIRONMENT = "local"
CORS_ORIGIN = "*"
