name = "abogados"
main = "_worker.js"
compatibility_date = "2025-01-01"
account_id = "70661c46051942965565a5c976219dde"
workers_dev = true

[build]
command = "npm run build"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "ABOGADO_WILSON_KV"
id = "0757f29fc8264ce985de8d780283d86e"

[[d1_databases]]
binding = "ABOGADO_WILSON_DB"
database_name = "abogadosecuador"
database_id = "0757f29fc8264ce985de8d780283d86e"

[triggers]
crons = [ "0 5 * * *" ]

[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
API_ENABLED = "true"
SUPABASE_URL = "https://kbybhgxqdefuquybstqk.supabase.co"
CLIENT_VERSION = "3.0.0"
N8N_WEBHOOK_URL = "https://n8n-latest-hurl.onrender.com"
WHATSAPP_NUMBER = "+59398835269"
CONTACT_EMAIL = "Wifirmalegal@gmail.com"
CLOUDINARY_CLOUD_NAME = "dg3s7tqoj"
APP_URL = "https://abogados.workers.dev"
API_URL = "https://abogados.workers.dev/api"
