name = "abogados-ecuador"
compatibility_date = "2025-01-01"
account_id = "70661c46051942965565a5c976219dde"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "ABOGADO_WILSON_KV"
id = "0757f29fc8264ce985de8d780283d86e"

[[d1_databases]]
binding = "ABOGADO_WILSON_DB"
database_name = "abogadosecuador"
database_id = "029949b9-4266-4060-8bcd-71525b26600c"

[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
API_ENABLED = "true"
SUPABASE_URL = "https://kbybhgxqdefuquybstqk.supabase.co"
CLIENT_VERSION = "3.0.0"
N8N_WEBHOOK_URL = "https://n8n-latest-hurl.onrender.com"
WHATSAPP_NUMBER = "+59398835269"
CONTACT_EMAIL = "ecuadorabogado1@gmail.com"
CLOUDINARY_CLOUD_NAME = "dg3s7tqoj"
CLOUDINARY_API_KEY = "673776954212897"
APP_URL = "https://abogados.ecuador.workers.dev"
API_URL = "https://abogados.ecuador.workers.dev/api"
PAYPAL_MODE = "live"
PAYPAL_CLIENT_ID = "AWxKgr5n7ex5Lc3fDBOooaVHLgcAB-KCrYXgCmit9DpNXFIuBa6bUypYFjr-hAqARlILGxk_rRTsBZeS"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtieWJoZ3hxZGVmdXF1eWJzdHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjAwODMsImV4cCI6MjA3MzEzNjA4M30.s1knFM9QXd8CH8TC0IOtBBBvb-qm2XYl_VlhVb-CqcE"

