name = "abogadosecuador"
main = "src/worker.js"
compatibility_date = "2025-01-01"
account_id = "06ea65e2b51d0f23f0c44f92962ac95d"
workers_dev = true

# Build configuration
[build]
command = "npm run build"

# Site configuration
[site]
bucket = "./dist"

# KV Namespaces
[[kv_namespaces]]
binding = "ABOGADO_WILSON_KV"
id = "9585583f15824e6891e9660bd6f85d7d"

# D1 Databases
[[d1_databases]]
binding = "ABOGADO_WILSON_DB"
database_name = "abogadosecuador"
database_id = "029949b9-4266-4060-8bcd-71525b26600c"

# Environment variables
[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
API_ENABLED = "true"
SUPABASE_URL = "https://kbybhgxqdefuquybstqk.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtieWJoZ3hxZGVmdXF1eWJzdHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjAwODMsImV4cCI6MjA3MzEzNjA4M30.s1knFM9QXd8CH8TC0IOtBBBvb-qm2XYl_VlhVb-CqcE"
CLIENT_VERSION = "3.0.0"
N8N_WEBHOOK_URL = "https://n8n-latest-hurl.onrender.com"
WHATSAPP_NUMBER = "+59398835269"
CONTACT_EMAIL = "Wifirmalegal@gmail.com"
CLOUDINARY_CLOUD_NAME = "dg3s7tqoj"
CLOUDINARY_API_KEY = "673776954212897"
PAYPAL_CLIENT_ID = "AWxKgr5n7ex5Lc3fDBOooaVHLgcAB-KCrYXgCmit9DpNXFIuBa6bUypYFjr-hAqARlILGxk_rRTsBZeS"
APP_URL = "https://abogadosecuador.workers.dev"

# Production environment
[env.production]
name = "abogadosecuador"
routes = [
  { pattern = "abogadosecuador.workers.dev/*", zone_name = "" }
]

# Production KV
[[env.production.kv_namespaces]]
binding = "ABOGADO_WILSON_KV"
id = "9585583f15824e6891e9660bd6f85d7d"

# Production D1
[[env.production.d1_databases]]
binding = "ABOGADO_WILSON_DB"
database_name = "abogadosecuador"
database_id = "029949b9-4266-4060-8bcd-71525b26600c"

# Production variables
[env.production.vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
API_ENABLED = "true"
SUPABASE_URL = "https://kbybhgxqdefuquybstqk.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtieWJoZ3hxZGVmdXF1eWJzdHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjAwODMsImV4cCI6MjA3MzEzNjA4M30.s1knFM9QXd8CH8TC0IOtBBBvb-qm2XYl_VlhVb-CqcE"
CLIENT_VERSION = "3.0.0"
N8N_WEBHOOK_URL = "https://n8n-latest-hurl.onrender.com"
WHATSAPP_NUMBER = "+59398835269"
CONTACT_EMAIL = "Wifirmalegal@gmail.com"
CLOUDINARY_CLOUD_NAME = "dg3s7tqoj"
CLOUDINARY_API_KEY = "673776954212897"
PAYPAL_CLIENT_ID = "AWxKgr5n7ex5Lc3fDBOooaVHLgcAB-KCrYXgCmit9DpNXFIuBa6bUypYFjr-hAqARlILGxk_rRTsBZeS"
APP_URL = "https://abogadosecuador.workers.dev"
